print ("Mark Christian M. Naling")
print ("Santol, Boac, Marinduque")
print ("March 04,2001")
print ("Marinduque State College")
print ("BSIT - 2A")
print ("Playing Online Games")
print ("Playing Music")
print ("Editing")
print ("Watching Movies")
print ("Playing Chess")